# Generated by Django 4.2.3 on 2023-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_donation_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
