# Generated by Django 4.2.3 on 2023-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_donation_picked_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='picked_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
