# Generated by Django 4.2.3 on 2023-07-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_donation_picked_up_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['picked_up']},
        ),
    ]
