# Generated by Django 4.2.3 on 2023-07-14 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_donation_options_alter_donation_picked_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='picked_up_time',
            field=models.TimeField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
    ]
