# Generated by Django 4.2.3 on 2023-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_donation_picked_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='picked_up_date',
            field=models.DateField(blank=True, default='2023-07-12', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='picked_up_time',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
