# Generated by Django 4.2.3 on 2023-07-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_donation_picked_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='picked_up_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
